### ISSUE TITLE
image de profil utilisateur

### ISSUE THREAD

**Issue by j314h** [j314h/sveltekit-test#22]
il faut ajouter une image pour l'utilisateur connecté
il y a déjà la colonne avatar de prévu dans la table profil
il faut juste creer un bucket et creer le input

il faut donner le choix donc
- l'utilisateur s'inscris, sans image au départ et donc utilise une image par défaut
qu'il faudra deja telecharger sur supabase et donc donner une valeur par défaut à la colone avatar du profil
- ensuite mettre un input pour modifier l'image du profil si l'utilisateur le veux (donc formulaire à part des autres modification du profil)

si d'autre idées proposer, ce fonctionnement n'est pas arreter peut etre on peux penser à quelque chose de plus simple pour l'utilisateur final

**Comment by David-Caignaert** [comment]
- [ ] coté api fichier index.json.ts
- [ ] coté api fichier [id]-bucket.json.ts
- [ ] coté front créer le component input-avatar

**Comment by j314h** [comment]
yop @David-Caignaert 
je te laisse regarder le commit que je viens de faire
donc du coup grosse misere, grosse perte de temps encore une fois, pour un truc que ... ben si tu sais pas jamais tu trouves
voici le lien qui ma fait trouver la réponse
[solution](https://github.com/supabase/supabase/discussions/2289#discussioncomment-999224)

bon je te remet le context

- user telecharge son image
=> PAS ENCORE D'IMAGE
- il a pas d'image on la creer dans le bucket avatars/public
- on recupere le lien qui dans la clé data.Key
- on prend ce lien on le met dans la colonne avatar du profil selectionné avec l'id du profil contenu dans le profiStore
- pour afficher l'image on a juste besoin d'appeller dans l'attribut src de la balise image
import.meta.env.url + profilStore.avatar
- l'image s'affiche
=> IL A DEJA UNE IMAGE
- avec la valeur upsert à true supabase modifie automatiquement le fichier si il a le meme nom
et il a le meme nom car on lui a donné le nom " idduuser + le type " (alors là je pose réserve car si le type n'est pas le meme il va en recreer un, on fera une nouvelle issus pour la version 2), donc il a le meme nom
supabase s'occupe de gerer la modification OK, MAIS NOTRE soucis était le cache (comme ecris dans la solution)
il y a un cache de 3600s par défaut 1 heure MY GOD !!!! du coup c'est pour ça que l'image ce modifiait pas 
(fallait le savoir sérieux !!!!!) bref, la suite reste la meme chose.

donc clairement ajouter, modifier sa fonctionne nickel
il reste 
- le design
- la suppression

et tout sera good

voila je te laisse gueter et continuer, sinon heu je t'ai ecris 2 fois dans une des pull request que j'ai fait pour te dire que j'avais finis je sais pas si t'avait vu mais si tu peux regarder et valider sa serais cool.
