### ISSUE TITLE
une 2éme façon de fermer le profil

### ISSUE THREAD

**Issue by David-Caignaert** [j314h/sveltekit-test#47]
Il faudrait que le profil se ferme quand on clic en dehors de la fenêtre car on peut continuer a utilisé la todo avec la fenetre profil ouverte

**Comment by j314h** [comment]
ok oui bonne idée, pense à mettre correctement les infos de l'issus sur la droite
car elle est relier à rien, pareil pour les pullrequest tu ma pas assigné et ta rien renseigné ;-)

**Comment by j314h** [comment]
je la passe en bug pour qu'elle soit prioritaire

**Comment by j314h** [comment]
@David-Caignaert suite à l'implémentation du volet profil avec dropdown de daisyui
il est compliquer d'avoir une fermeture avec la croix + clique en dehors du volet

le soucis qu'on avait c'etait que quand on modifait le profil le volet du profil ce fermais tous seul à cause du dropdown
du coup grace au notification cela ne semble plus etre un probleme et on économise un cliquer à fermer le volet
je trouve ça beaucoup mieux.

du coup le veritable fonctionnement est 
clique sur le logo profil => ouverture
clique n'importe où => fermeture
pour moi sa va ce comportement ne me dérange pas
affecter un btn avec croix pour fermé semble compliquer sans tous changer
peux pour une v2 si cela dérange vraiment

je te laisse donner ton avis
