### ISSUE TITLE
creer composant notification et implementer au endroit propice

### ISSUE THREAD

**Issue by j314h** [j314h/sveltekit-test#5]
j'ai l'idée d'une banniere qui s'affiche avec un settimeout
on pourra gerer tout les cas , positif, avertissement, error

adapter un composant avec daisyui sera plus rapide 
au besoin discuton du design et du comportement

**Comment by j314h** [comment]
je suggere de mettre un bouton de fermeture manuel de la notification afin de donnée le temps à l'utilisateur de lire
les notifications courte d'info peu importante doivent avoir un minuteur les autre doivent etre supprimer manuellement

**Comment by David-Caignaert** [comment]
- [ ] créer le component notification
- [ ] créer un enum
- [ ] créer le store
- [ ] faire la liste des differente notification qui existe deja sur le projet

**Comment by j314h** [comment]
@David-Caignaert  
n'oublie pas que les issus #27 ; #18 ; #15 sont lier à cette issus que tu fais
car une fois le composant fait tu peux implémenter ton composant par rapport à ces issus pour tester ton composant

**Comment by j314h** [comment]
@David-Caignaert parlons ici c'est mieux

je sais pas si la cloche verte à droite soit une bonne idée on aurait tendence à croire qu'il est clicable
je le verrais plutot en haut à gauche

**Comment by David-Caignaert** [comment]
du coup pour les issus#27 #18 #15 je dois merge main dans ma branche?

**Comment by j314h** [comment]
> du coup pour les issus#27 #18 #15 je dois merge main dans ma branche?

sa dépends tu as besoin de ce qu'il y a dans main
mais je pense que oui car il y a eu pas mal de nouveauté

**Comment by David-Caignaert** [comment]
![dependence](https://user-images.githubusercontent.com/71434542/153150483-a46aa59b-5bbe-4d49-a742-ee1e0859218b.png)

**Comment by David-Caignaert** [comment]
voila je pense que ca fait mieux comme ca

**Comment by j314h** [comment]
@David-Caignaert 
ouai c'est mieux, juste le fond faut que ce soit cohérant avec le fond du profil
et je pense il a un soucis avec le bord arrondie du haut

**Comment by j314h** [comment]
sauf erreur de ma part les notif on pas le meme fond que le fond du profil ?
je sais pas trop si mon écran d'ordi déconne mdrr

**Comment by j314h** [comment]
franchement sa ce peux que ce soit mon ecran

**Comment by David-Caignaert** [comment]
ha j'ai fait le border et le bouton quitter mais pas le fond

**Comment by David-Caignaert** [comment]
oki

**Comment by j314h** [comment]
si jamais tu l'as pas fait, le fait pas je m'en occupe en meme temps que l'issus #53 
tu me redira

**Comment by j314h** [comment]
c'est ok je viens de le faire je clos
