### ISSUE TITLE
tooltips de daisyui peut etre ajouter

### ISSUE THREAD

**Issue by j314h** [j314h/sveltekit-test#6]
certain bouton ou lien de text je pense on besoin de tooltips (voir daisyui) implementer

**Comment by j314h** [comment]
@David-Caignaert tu regarderas les tooltips chez daisyui je voulais mettre ça à certain endroit 
on les ciblera et validera apres deja juste savoir si tu penses que c'est cool ou si sa fait trop

**Comment by David-Caignaert** [comment]
je regarde ça après
